version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: payment_postgres
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: payment_user
      RABBITMQ_DEFAULT_PASS: payment_pass
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data: