spring.application.name=momer-payments-vop

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate
